plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace = "com.northstarlabs.avionics.altimeter"
    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }

    defaultConfig {
        applicationId = "com.northstarlabs.avionics.altimeter"
        // WFF v1 and sweep seconds are supported from Wear OS 4 / API 33.
        minSdk = 33
        targetSdk = 36
        versionCode = 1
        versionName = "0.1.0"

    }

    buildTypes {
        debug {
            // Resource-only WFF packages must not contain a generated classes.dex.
            isMinifyEnabled = true
        }
        release {
            // R8 removes the otherwise-empty dex generated by the app plugin.
            isMinifyEnabled = true
            // WFF resources are discovered by the system renderer, not app code.
            isShrinkResources = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    enableKotlin = false
}

dependencies {
}
